app-site/src/Entity/Detections.php
<?php

namespace App\Entity;

use App\Repository\DetectionsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetectionsRepository::class)]
class Detections
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $image_filename = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    public ?\DateTimeInterface $triggered_at = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Couple $couple = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageFilename(): ?string
    {
        return $this->image_filename;
    }

    public function setImageFilename(?string $image_filename): static
    {
        $this->image_filename = $image_filename;

        return $this;
    }

    public function getTriggeredAt(): ?\DateTimeInterface
    {
        return $this->triggered_at;
    }

    public function setTriggeredAt(\DateTimeInterface $triggered_at): static
    {
        $this->triggered_at = $triggered_at;

        return $this;
    }

    public function getCoupleId(): ?Couple
    {
        return $this->couple;
    }

    public function setCoupleId(?Couple $couple): static
    {
        $this->couple = $couple;

        return $this;
    }
}

app-site/templates/components/alert.html.twig
<div class="alert-container">
    {% for message in app.flashes('success') %}
        <div class="alert success" onclick="this.style.display='none';">
            <i class="fa-solid fa-check"></i> <strong>Success!</strong> {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('error') %}
        <div class="alert error" onclick="this.style.display='none';">
            <i class="fa-solid fa-xmark"></i> <strong>Error!</strong> {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('warning') %}
        <div class="alert warning" onclick="this.style.display='none';">
            <i class="fa-solid fa-triangle-exclamation"></i> <strong>Warning!</strong> {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('info') %}
        <div class="alert info" onclick="this.style.display='none';">
            <i class="fa-solid fa-circle-info"></i> {{ message }}
        </div>
    {% endfor %}
</div>

<script>
    let alerts = document.getElementsByClassName("alert");
    for (let i = 0; i < alerts.length; i++) {
        setTimeout(function(){ alerts[i].style.display = "none"; }, 5000);
    }
</script>

app-site/templates/components/confirmdialog.html.twig
<dialog id="confirm-modal" class="modal-wrapper">
    <div class="modal">
        <div class="header">
            <h2 class="title">{{ title }}</h2>
            <button type="button" class="close-btn" onclick="document.getElementById('confirm-modal').close()">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="p-icon p-button-icon" aria-hidden="true"><path d="M8.01186 7.00933L12.27 2.75116C12.341 2.68501 12.398 2.60524 12.4375 2.51661C12.4769 2.42798 12.4982 2.3323 12.4999 2.23529C12.5016 2.13827 12.4838 2.0419 12.4474 1.95194C12.4111 1.86197 12.357 1.78024 12.2884 1.71163C12.2198 1.64302 12.138 1.58893 12.0481 1.55259C11.9581 1.51625 11.8617 1.4984 11.7647 1.50011C11.6677 1.50182 11.572 1.52306 11.4834 1.56255C11.3948 1.60204 11.315 1.65898 11.2488 1.72997L6.99067 5.98814L2.7325 1.72997C2.59553 1.60234 2.41437 1.53286 2.22718 1.53616C2.03999 1.53946 1.8614 1.61529 1.72901 1.74767C1.59663 1.88006 1.5208 2.05865 1.5175 2.24584C1.5142 2.43303 1.58368 2.61419 1.71131 2.75116L5.96948 7.00933L1.71131 11.2675C1.576 11.403 1.5 11.5866 1.5 11.7781C1.5 11.9696 1.576 12.1532 1.71131 12.2887C1.84679 12.424 2.03043 12.5 2.2219 12.5C2.41338 12.5 2.59702 12.424 2.7325 12.2887L6.99067 8.03052L11.2488 12.2887C11.3843 12.424 11.568 12.5 11.7594 12.5C11.9509 12.5 12.1346 12.424 12.27 12.2887C12.4053 12.1532 12.4813 11.9696 12.4813 11.7781C12.4813 11.5866 12.4053 11.403 12.27 11.2675L8.01186 7.00933Z" fill="currentColor"></path></svg>
            </button>
        </div>
        <div class="content">
            <span class="fa-solid fa-warning"></span>
            <p>{{ message }}</p>
        </div>
        <div class="footer">
            <button class="cancel-btn" onclick="document.getElementById('confirm-modal').close()">Cancel</button>
            <a class="confirm-btn" href="{{ confirmUrl }}">Confirm</a>
        </div>
    </div>
</dialog>

app-site/templates/components/couplecard.html.twig
<a class="img-card-wrapper" href="{{ path('app_couples_view', {id: couple.coupleEntity.id}) }}">
    <div class="img-card">
        <img src="{{ path('app_couples_capture', {id: couple.coupleEntity.id}) }}" alt="preview">
        <div class="dark-overlay"></div>
        <div class="infos">
            <div class="couple-name">
                <p>{{ couple.coupleEntity.title }}</p>
            </div>
            <div class="couple-status">
                {% if couple.actionStatus.buzzerEnabled %}
                    <span class="fa-solid fa-bell red"></span>
                {% endif %}
                <span class="fa-solid fa-wifi {{ couple.lowerRssi.color }}"></span>
                <span class="fa-solid fa-power-off {{ couple.coupleEntity.enabled == true ? "green" : "red"  }}"></span>
            </div>
        </div>
    </div>

    {% if couple.newDetectionCount > 0 %}
        <div class="notif">
            <span class="fa-solid fa-bell"></span>
            <span>{{ couple.newDetectionCount }}</span>
        </div>
    {% endif %}
</a>

app-site/templates/components/detectioncard.html.twig
<a class="card item" href="{{ path('app_detections_view', {id: detection.id}) }}">
    <div class="infos">
        <p class="date">{{detection.triggeredAt|date("d/m/Y H:i:s")}}</p>
        <p class="type">Movements</p>
        <p class="source">{{ coupleName }}</p>
    </div>
    <img class="preview" src="{{ path('app_detections_image', {filename: detection.imageFilename}) }}" alt="détéction">
</a>

app-site/templates/components/edittitlemodal.html.twig
<dialog id="edit-modal" class="modal-wrapper">
    <div class="modal">
        <div class="header">
            <h2 class="title">{{message}}</h2>
            <button type="button" class="close-btn"
                    onclick="document.getElementById('edit-modal').close()">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8.01186 7.00933L12.27 2.75116C12.341 2.68501 ... Z" fill="currentColor"/>
                </svg>
            </button>
        </div>

        <form method="post" action="{{ path('app_couple_update_name', {id: couple.coupleEntity.id}) }}">
            <div class="content">
                <label for="couple-title">New title :</label>
                <input id="couple-title" name="title" type="text" value="{{ couple.coupleEntity.title }}" required autofocus />
            </div>
            <div class="footer">
                <button type="button" class="cancel-btn"
                        onclick="document.getElementById('edit-modal').close()">
                    Annuler
                </button>
                <button type="submit" class="confirm-btn">
                    Enregistrer
                </button>
            </div>
        </form>
    </div>
</dialog>

app-site/templates/components/navigation.html.twig
<nav class="sidebar">
    <div class="top">
        <div class="header">
            <img src="{{ asset('icons/sentinel.svg') }}" alt="Logo" class="logo">
            <p>Sentinel</p>
        </div>
        <a class="nav-item {{ index == 0 ? "active" : ""  }}" href="{{ path('app_couples') }}">
            <span class="icon fa-solid fa-camera"></span>
            <span class="text">Alarms</span>
        </a>
        <a class="nav-item {{ index == 1 ? "active" : ""  }}" href="{{ path('app_detections') }}">
            <span class="icon fa-solid fa-bolt"></span>
            <span class="text">Detections</span>
        </a>
        <a class="nav-item {{ index == 2 ? "active" : ""  }}" href="{{ path('app_settings') }}">
            <span class="icon fa-solid fa-gear"></span>
            <span class="text">Settings</span>
        </a>
    </div>

    <div class="bottom">
        {% if app.user %}
            <a class="user-info" href="{{ path('app_account_edit', {id: app.user.getId() }) }}">
                <span class="icon fa-solid fa-user"></span>
                <span class="text">{{ app.user.getUsername() }}</span>
            </a>
            <a href="{{ path('app_logout') }}" class="icon-btn">
                <span class="fa-solid fa-power-off"></span>
            </a>
        {% endif %}
    </div>
</nav>

<nav class="topbar">
    <div class="logo">
        <img src="{{ asset('icons/sentinel.svg') }}" alt="Logo" class="logo">
        <p>Sentinel</p>
    </div>
    <button class="icon-btn mobile-menu-button">
        <span class="fa-solid fa-bars"></span>
    </button>
    <div class="sidebar mobile mobile-menu">
        <div class="top">
            <a class="nav-item {{ index == 0 ? "active" : ""  }}" href="{{ path('app_couples') }}">
                <span class="icon fa-solid fa-camera"></span>
                <span class="text">Alarms</span>
            </a>
            <a class="nav-item {{ index == 1 ? "active" : ""  }}" href="{{ path('app_detections') }}">
                <span class="icon fa-solid fa-bolt"></span>
                <span class="text">Detections</span>
            </a>
            <a class="nav-item {{ index == 2 ? "active" : ""  }}" href="{{ path('app_settings') }}">
                <span class="icon fa-solid fa-gear"></span>
                <span class="text">Settings</span>
            </a>
        </div>
        <div class="bottom">
            {% if app.user %}
                <a class="user-info" href="{{ path('app_account_edit', {id: app.user.getId() }) }}">
                    <span class="icon fa-solid fa-user"></span>
                    <span class="text">{{ app.user.getUsername() }}</span>
                </a>
                <a href="{{ path('app_logout') }}" class="icon-btn">
                    <span class="fa-solid fa-power-off"></span>
                </a>
            {% endif %}
        </div>
    </div>
</nav>